### ISSUE TITLE
Feature Request - Kong Mesh (Kuma)

### ISSUE THREAD

**Issue by FabianHardt** [FabianHardt/k3d-bootstrap-cluster#11]
## Kuma / Kong Mesh
It would be nice to have a Kuma / Kong mesh example as well. Version 2.0 of Kuma was recently released very freshly. 
So another example would be possible here...

**Comment by d4kine** [comment]
Added the example and added a pull request: https://github.com/FabianHardt/k3d-bootstrap-cluster/pull/13

Feel free to merge, contact me or re-assign the issue.

**Comment by FabianHardt** [comment]
First version implemented with #13
