### ISSUE TITLE
Just delete k3d Cluster created by create-sample.sh script

### ISSUE THREAD

**Issue by svenbernhardt** [FabianHardt/k3d-bootstrap-cluster#14]
Currently the shell script create-sample.sh script deletes all k3d Clusters that have been configured, which might not be desired by users.

This behavior should be changed, so that only the Cluster created by the script is deleted while creating a new one.

**Comment by FabianHardt** [comment]
My goal here was to first remove the cluster in any case, which is to be newly created in the next step.

It may therefore make sense to work with the cluster name queried in the first dialog.

**Comment by FabianHardt** [comment]
@svenbernhardt  I've created a possible fix for that. Take a look at #15 and give me some feedback :-)
